trigger: none
pr: none
# resources:
#   pipelines:
#     - pipeline: test
#       source: azure-iot-services-dotnet.ci.test
#       trigger:
#         branches:
#           - master
pool:
  vmImage: ubuntu-latest
variables:
  masterBranch: refs/heads/master/
  sourceBranch: $[coalesce(variables.resources.pipeline.test.sourceBranch, variables.Build.SourceBranch)]
  imageTag: $[coalesce('latest')]
stages:
  - stage: printPipelineResourceVariables
    displayName: Print pipeline resource variables
    jobs:
      - job: printPipelineResourceVariables
        displayName: Print pipeline resource variables
        steps:
          - template: ../templates/print-pipeline-resource-variables.yaml
            parameters:
              pipelineResourceName: test

  - stage: crslDev
    displayName: CRSL dev
    dependsOn: []
#     condition: or(eq(variables['resources.pipeline.test.sourceBranch'], variables['masterBranch']), eq(variables['resources.pipeline.test.sourceBranch'], Null), eq(variables['resources.pipeline.test.sourceBranch'], ''))
    jobs:
      - template: ../templates/jobs-deploy-code.yaml
        parameters:
          environmentName: IoT_Demo
          subscriptionName: 3M-IoT-Demo
          applicationCode: iotdemo
          applicationShortCode: iotd
          environmentCategory: test
          imageTag: $(imageTag)
