trigger: none
pr: none
pool:
  vmImage: ubuntu-latest
variables:
  platformOperationServiceConnection: 3M-IoT-Demo
  locationName: centralus
stages:
  - stage: newEnv
    displayName: New Environment
    dependsOn: []
    jobs:
      - template: ../templates/jobs-deploy-infra.yaml
        parameters:
          subscriptionName: 3M-IoT-Demo
          locationName: $(locationName)
          environmentName: IoT_Demo
          subscriptionId: c36fb2f8-f98d-40d0-90a9-d65e93acb428
          applicationCode: iotdemo
          applicationShortCode: iotd
          environmentCategory: test
          platformOperationServiceConnection: $(platformOperationServiceConnection)
          k8sVersion: 1.16.7
